In [1]:
import pandas as pd

data = pd.read_csv("/content/tennis.csv")
data.info()
data.columns
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   outlook   14 non-null     object
 1   temp      14 non-null     object
 2   humidity  14 non-null     object
 3   windy     14 non-null     bool
 4   play      14 non-null     object
dtypes: bool(1), object(4)
memory usage: 590.0+ bytes

    outlook  temp humidity  windy play
0     sunny   hot     high  False   no
1     sunny   hot     high   True   no
2  overcast   hot     high  False  yes
3     rainy  mild     high  False  yes
4     rainy  cool   normal  False  yes

In [2]:
# outlook_count = data.groupby(['outlook', 'play']).size()

# outlook_total = data.groupby(['outlook']).size()
# temp_count = data.groupby(['temp', 'play']).size()
# temp_total = data.groupby(['temp']).size()
# humidity_count = data.groupby(['humidity', 'play']).size()
# humidity_total = data.groupby(['outlook']).size()
# windy_count = data.groupby(['windy', 'play']).size()
# windy_total = data.groupby(['windy']).size()
# print(outlook_count)
# print(windy_total)
# print(outlook_total)
# print(temp_count)
# print(temp_total)
# print(humidity_count)
# print(humidity_total)
# print(windy_count)
# print(windy_total)
# p_over_yes = outlook_count['overcast','yes']
# p_over_no = 0
# p_rainy_yes = outlook_count['rainy','yes']
# p_rainy_no = outlook_count['rainy','no']
# p_rainy_yes = outlook_count['sunny', 'yes']
X_train = pd.get_dummies(data[['outlook', 'temp', 'humidity', 'windy']])
y_train = pd.DataFrame(data['play'])
#assigning predictor and target variables
#x= np.array([[-3,7],[1,5], [1,2], [-2,0], [2,3], [-4,0], [-1,1], 
#[1,1], [-2,2], [2,7],[-4,1], [-2,7]])
#Y = np.array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4])
print(X_train.info())
print(X_train.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   windy             14 non-null     bool
 1   outlook_overcast  14 non-null     uint8
 2   outlook_rainy     14 non-null     uint8
 3   outlook_sunny     14 non-null     uint8
 4   temp_cool         14 non-null     uint8
 5   temp_hot          14 non-null     uint8
 6   temp_mild         14 non-null     uint8
 7   humidity_high     14 non-null     uint8
 8   humidity_normal   14 non-null     uint8
dtypes: bool(1), uint8(8)
memory usage: 254.0 bytes
None
   windy  outlook_overcast  ...  humidity_high  humidity_normal
0  False                 0  ...              1                0
1   True                 0  ...              1                0
2  False                 1  ...              1                0
3  False                 0  ...              1                0
4  False                 0  ...              0                1

[5 rows x 9 columns]

In [3]:
#Import Library of Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
import numpy as np
#Create a Gaussian Classifier
model = GaussianNB()
# Train the model using the training sets
model.fit(X_train, y_train)
#Predict Output
predicted= model.predict([[False,1,0,0,0,1,0,1,0]])
print (predicted)

['yes']

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)